GET http://myprojects.dev/api/auth

### signup
POST http://myprojects.dev/api/auth/signup
Content-Type: application/json

{
  "email": "string@string.com",
  "name": "string",
  "password": "abc123",
  "phonenumber": "123456"
}

### role assign
POST http://myprojects.dev/api/auth/64ed4246e39c338c492f8381/role
Content-Type: application/json
