### Get Products
GET https://myprojects.dev/api/products
Content-Type: application/json

### Get Product By Id
GET https://myprojects.dev/api/products/650a8a5b1c6df48b3c8786ac
Content-Type: application/json

### Create Product
POST https://myprojects.dev/api/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 10.00,
  "categoryName": "Drink",
  "description": "This is description"
}

### Delete Product By Id
DELETE https://myprojects.dev/api/products/650aa0269e7ed164b5be9a1c
Content-Type: application/json