### Get Products
GET http://myprojects.dev/api/products
Content-Type: application/json

### Get Product By Id
GET http://myprojects.dev/api/products/650a8a5b1c6df48b3c8786ac
Content-Type: application/json

### Create Product
POST http://myprojects.dev/api/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 10.00,
  "categoryName": "Drink",
  "description": "This is description"
}

### Delete Product By Id
DELETE http://myprojects.dev/api/products/650a968abe18960777cf409b
Content-Type: application/json