apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: nerojz/food-auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-svc:27017/auth'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  ports:
    - name: auth-svc-port
      protocol: TCP
      port: 3000
      targetPort: 3000
