apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.1
          args: ['start-dev']
          env:
            - name: KEYCLOAK_ADMIN
              value: 'admin'
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: 'admin'
            - name: KC_HOSTNAME
              value: myprojects.dev
            - name: KC_HOSTNAME_ADMIN
              value: myprojects.dev/keycloak
            - name: KC_HOSTNAME_PATH
              value: /keycloak
            - name: KC_HOSTNAME_STRICT
              value: 'false'
            - name: KC_PROXY
              value: 'edge'
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  # type: LoadBalancer
  ports:
    - name: http
      port: 53582
      targetPort: 8080
